title:              统计小站
tagline:            By kausiujik
description:        目录：文章列表
url:                http://kausiujik.github.io

author:
  name:             kausiujik
  url:              https://twitter.com/watt16
  email:            watthu@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
